### ISSUE TITLE
Egyptian Empire Mechanic

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#110]
A system of imperial revival like what LoR gave to Byzantium.
Perhaps an Imperial title that begins with only Egypt (and Nubia?) as de jure (transfer de jure status via event), but on reclamation of old territories, stuff gets redrawn.

Use [this map](https://en.wikipedia.org/wiki/New_Kingdom_of_Egypt) and [this map](https://en.wikipedia.org/wiki/Ptolemaic_Kingdom#/media/File:PtolemaicEmpire_(cropped).png) for the most part for territories.

**Comment by secretfire42** [comment]
Again, pretty cool!

**Comment by xirsoi** [comment]
this has been done for months
