### ISSUE TITLE
Sed Festival for Kemetics

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#12]
As suggested in [rquinio's post here](http://forum.paradoxplaza.com/forum/showthread.php?829413-Ancient-Religions-Reborn!&p=18701184&viewfull=1#post18701184), the Sed festival would be a great bit of flavor for the Kemetic pagans.
http://en.wikipedia.org/wiki/Sed_festival

**Comment by xirsoi** [comment]
I'm not sure how to do the every three years bit. I imagine a decaying flag would be best.
Suppose we'll have to do something similar when we implement the Olympian Games.

**Comment by rquinio** [comment]
Yep, either flag or modifier. 
Modifiers seem natural, but can't be removed via console command for testing:

    NOT = { has_character_modifier = held_sed_festival_timer }

    add_character_modifier = {
	name = held_sed_festival_timer
	duration = 1080
	hidden = yes
    }

I've tried using variables to have an incremental effect each time decision is taken, so that there is a reward to follow tradition, which seems to kind-of work.
Not sure about the effects, maybe:
- incremental piety gain: 200 + 50* nb_festival ?
- health modifier: +1 for 1 year ? - you feel rejuvenated... literally  :)
- general opinion: +10 for 1 year ? - your right to rule is recognized

> On the first day, the king presented offerings to the gods; then was seated and crowned on a raised platform provided with two thrones that represented Upper and Lower Egypt. Images of provincial deities in a series of shrines were shown beside the double throne, specifically the cobra-goddess Wadjet of the Delta town of Buto, and the vulture goddess Nekhbet of el-Kab; symbols of Upper and Lower Egypt. The priests carried the statues of the gods and presented offerings, in a sign of giving thanks for past loyalty or to secure good relationships in the future. 

> The king was then attired a short kilt with a bull's tail in its back, which probably gave the festival a less formal name: "The Feast of the Tail". In the open space between the two rows of shrines, the king ran a ritual race alongside the Apis Bull four times as the ruler of Lower Egypt wearing the Red Crown, and four times as that of Upper Egypt wearing the White Crown. The course was bounded by two points symbolizing the borders of Egypt to reinforce his dominion over the whole kingdom, and at the same time he dedicates it to the gods. In doing so, he proved that he was still physically able to rule the country, and was thus rejuvenated and reborn. Finally, he was carried in a procession to visit the chapels of the gods. He was carried first as king of Lower Egypt by the "Great Ones of Upper and Lower Egypt" to the chapel of Horus, where he receives the crook and the flail. Next, as king of Upper Egypt, he was carried to the two chapels of Horus of Edfu and Seth of Ombos, where he was handed a bow and arrow, with which he shoots an arrow in each one of the four directions.

**Comment by xirsoi** [comment]
Those bonuses seem reasonable to me.

I think it would be cool if there was a chance you might be unable to complete the race, resulting in a general opinion malus. Certain traits and attributes could affect it, like Gluttony, Sloth, or low Health.

**Comment by rquinio** [comment]
Ok, I got a proposal for review: https://github.com/xirsoi/ancientreligions/pull/21
I've split the chain into 3 days, and based on your suggestion, each time there is a small change that something goes wrong, causing the festival to abort :)
- offerings (Pharaoh falls asleep)
- race (unable to complete)
- bow & arrow (shoots someone)

**Comment by rquinio** [comment]
Closing as merged on develop !
