### ISSUE TITLE
Immortals

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#127]
Small chance that one of the immortal characters that can show up will be an appropriate type of 
 pagan (Germanic cultured character would be norse_pagan (never the reformed version, even after reformation), for instance).

**Comment by xirsoi** [comment]
The events that spawn the immortal characters are a little... tricky. They will have to be modified rather heavily, but there is room for improvement. Alternate versions of each character can be created, some even using dead cultures.

**Comment by secretfire42** [comment]
You can spawn characters from dead cultures? .... that leads to some INTERESTING kemetic revival events.

**Comment by xirsoi** [comment]
You can actually specify any in game culture when spawning a new character.
