### ISSUE TITLE
Egyptian CoA 

### ISSUE THREAD

**Issue by secretfire42** [xirsoi/ancientreligions#134]
Sorry I didn't put the Bug label on this, I don't use github very much and couldn't figure out how to do it. The Egyptian CoA show up in ruler designer, and randomly generated courtiers in game, but they do not show up under "dynasty customization" like all of the other CoA (including your other custom CoA) do. So if you forget to choose one in ruler designer, or use a pregenerated character, or the bugs of the base game switch it to a default due to empire creation, you loose it forever, as you can't just go in and choose one. Not sure why.

**Comment by xirsoi** [comment]
I'll investigate this, thanks for reporting!

**Comment by xirsoi** [comment]
Figured it out; You can't choose CoA styles for Pre-Reformed religions.
I'll mention this on the forums and hopefully the devs can squeeze in a change for the next patch.

Closing this ticket.
