### ISSUE TITLE
Prometheanism

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#14]
I think a hellenic heresy around the worship of Prometheus would be cool. Prometheus arguably did more for humanity than any other divine. His brother Epimetheus may also play a part in such a heresy.

Problem is, I haven't been able to come up with any interesting mechanical distinctions to make for them. We'd also need some kind of flavor events, since Prometheans wouldn't want much to do with Olympian traditions.

**Comment by xirsoi** [comment]
Input?

**Comment by jbelig** [comment]
This is an interesting concept for a heresy, especially in the age of the game (though totally ahistorical, but so is the whole mod). It could be considered monotheistic and is actually close to the idea of christianity and islam. Think about it, christians have the son of god, muslims have the prophet, now Prometheus is the lesser god who stepped up and now suffers for the shake of humanity!
This can be good, but I'm a bit occupied with work this week and tbh it's waaay easier to deal with some 'mindless' graphic or scripting job than come up with cool ideas.

**Comment by rquinio** [comment]
In case it can generate ideas, WtWSMS mod has:
- some mystery cults (Cybelian, Mastimani, Mithraic). But to me that seems more like sects (not sure if indian mechanism can work for pagans ?) than heresies, as a secret cult wouldn't convert an entire provinces....
- Neoplatonism http://en.wikipedia.org/wiki/Neoplatonism, seems interesting.

**Comment by xirsoi** [comment]
Mystery cults sound great and I think we should put them in at some point, but you're right, they aren't really heresy material. Definitely could provide inspiration for mechanics and flavor though, especially Neoplatonism.

**Comment by jbelig** [comment]
CK2 plus also has some cults represented by traits. They have an event chain that leads you to a mithraic mystery cult. It's a bit bland though, every 5 years you request a promotion and you get a reply that you're upgraded to the next level and you get a trait that gives opinion bonus.
Neoplatonism could lead to nice things, but yeah, not really good for a heresy.

**Comment by xirsoi** [comment]
Prometheanism could possibly give a +1 to Learning. A triggered modifier could cover that.

**Comment by xirsoi** [comment]
New ideas, give Prometheanism the designate heir mechanic and the piety gain while at peace bonus. Also throw in a lower short reign penalty (either reducing it to the default of 2 that non-pagans use, or go even lower to 1). These could represent their focus on civilization and enlightenment. They tend to have more peaceful successions as a result.

Perhaps give them a bonus to defense and a penalty to offense, encouraging acquisition of power and land by methods other than war. After all, Prometheus did everything through guile or diplomacy, no where do we see him commit an act of violence.

**Comment by xirsoi** [comment]
Okay, I'm almost done with both, but I've come across a stumbling block.
I need a flag for the head of promethean paganism. I spent about an hour of sheer frustration trying to make a simple one on my own in GIMP but came out of it with nothing but a headache, fury, and a super ugly image.

jbelig, could you put something together? Really simple; a hand holding fire against a white background. Nothing fancy required.

**Comment by jbelig** [comment]
Actually, when I was making hellenic coas I stumbled upon a few vases picturing Prometheus tied on the rock and the eagle eating his liver. Are you sure you don't want something like that?

**Comment by xirsoi** [comment]
Nah, too gruesome for their CoA. They recognize and appreciate his sacrifice for humanity, but focus more heavily on his gifts to them. The hand giving the fire is what I want.

**Comment by jbelig** [comment]
Yeah, you're right. Not to mention that the most common image that I found is this one, where the blood looks like he's taking a dump...
![promitheus](https://cloud.githubusercontent.com/assets/10557393/5895645/4fae35e0-a52e-11e4-95ea-a5b0dbbdb44f.jpg)

**Comment by jbelig** [comment]
Something like that?

![untitled](https://cloud.githubusercontent.com/assets/10557393/5896435/15ea13aa-a53e-11e4-9cc3-f138981bdb77.jpg)

That's how it looks in game:

![2015-01-26_00001](https://cloud.githubusercontent.com/assets/10557393/5896436/212e73c8-a53e-11e4-9ce3-543f805121d6.jpg)

**Comment by xirsoi** [comment]
Beautiful jbelig! Do you want to add the file to the appropriate branch of the repo, or email it to me and have me do it?

**Comment by jbelig** [comment]
I tried to clone the heresies branch but got the message that it's not supported for me version of windows (xp) so I emailed it.
This will probably be fixed the next couple of weeks. I'm fixing my second pc and I'll have windows 7 on it.

**Comment by xirsoi** [comment]
Now the question is, do I bother to add Holy Orders?

**Comment by jbelig** [comment]
Ask CK2+ to import theirs? They have two and I said I was going to research if there's any hint of historical justification but I forgot...

**Comment by xirsoi** [comment]
That's fine for the Hellenic Holy Order(s), but I meant a holy order for each of the heresies.
I think I'm fine leaving them without one for now.

I'll make an issue to add Holy Orders to both and some kind of celebration for Promethean in some future release.

**Comment by xirsoi** [comment]
Completed.
