### ISSUE TITLE
I can't become secretly hellenic bug

### ISSUE THREAD

**Issue by Lietuvis** [xirsoi/ancientreligions#144]
Don't get any decision to become secretly hellenic,i tried to make a custom character and then become secretly Hellenic,it didn't work,the falsly convert decision just kept me as a hellenic.also it says that now most  of the events make you secretly Hellenic,i tried every revival event chain (execpt the philosopher event revival)it just makes me hellenic.

**Comment by Lietuvis** [comment]
#bug

**Comment by xirsoi** [comment]
Steam Workshop or manual install?
What start date and which ruler did you replace?

If you used the workshop version, please try again.

**Comment by Lietuvis** [comment]
Manual install,when i installed the steam version had a blackout,i used the count of demetrias in the earliest bookmark

**Comment by xirsoi** [comment]
Thanks, I'll investigate this tonight after work.

**Comment by Lietuvis** [comment]
Thanks!

**Comment by xirsoi** [comment]
This is not a bug, Demetria isn't a holy site for anyone.

The Let's. Get. PAGAN! Decision intentionally makes you publicly pagan. Hold a holy site of Hellenism and right click the shield for the county. There will be a decision to secretly convert. It requires 250 piety though, just like the vanilla decisions.

**Comment by Lietuvis** [comment]
Ok thanks also another problem, you mean the falsely convert desicion? it doesn't work all it does for me is remove 250 piety.

**Comment by xirsoi** [comment]
Are you looking in the right place? Your secret religion shows up right next to your public religion on your character sheet.

These decisions were literally copy-pastes of the vanilla decisions and of each other. I know for a fact the Celtic one works, so I have a hard time believing the Hellenic one is broken.

**Comment by Lietuvis** [comment]
I know,i played the update in which the societies were added,I got the trait now but the form the order of secret hellenes decision doesn't appear.

**Comment by Lietuvis** [comment]
Also i get two new decisions named revoke_allowed and ai_will_do

**Comment by xirsoi** [comment]
There isn't a trait anymore, you are on an old version if the mod.  Polemos
didn't include these decisions.

I suggest you update to Cadmus, your saves will almost certainly work, and
your secret trait will be automatically turned into your secret religion.

**Comment by Lietuvis** [comment]
Ok thanks

**Comment by Lietuvis** [comment]
Umm i just updated on steam and i can't play as any christian character says that i can't play as secret religion

**Comment by xirsoi** [comment]
Make sure you uninstall the manual version too. I'll investigate sometime tonight.

**Comment by Lietuvis** [comment]
Ok

**Comment by xirsoi** [comment]
Fix is on Steam

**Comment by Lietuvis** [comment]
Thanks!

**Comment by Lietuvis** [comment]
![018](https://cloud.githubusercontent.com/assets/26690001/25961773/be0d5170-367b-11e7-835e-4c78cc777300.jpg)
![019](https://cloud.githubusercontent.com/assets/26690001/25961774/be11d4fc-367b-11e7-860b-6e47ba21ee90.jpg)
I got another bug,this isn't connected to hellenism but since it affects it ill put it here,i can't play any christian character(also i am an idiot because i only remembered the screenshot on steam when i was writing it XD,so sorry for poor quality,i took it with my phone)

**Comment by xirsoi** [comment]
Please open a new bug and include your checksum. It'll be in the bottom left of the main menu. It can take a little while to be calculated.

**Comment by Lietuvis** [comment]
Ok thanks!
