### ISSUE TITLE
Missing sprite

### ISSUE THREAD

**Issue by IhateTrains** [xirsoi/ancientreligions#159]
`GFX_evt_market_stalls` is missing

**Comment by xirsoi** [comment]
Thanks! It's probably a typo, as I meant to use the market stalls event pic from the summer faire.

**Comment by xirsoi** [comment]
Fixed on develop

**Comment by IhateTrains** [comment]
Great!
BTW, could you make me a collaborator? I think I could have more fixes and tweaks for you. I would create a branch and post my fixes there instead of messing with my outdated fork or creating issues that require a lot of your attention.
