### ISSUE TITLE
Duplicate hold_tristeria decision

### ISSUE THREAD

**Issue by IhateTrains** [xirsoi/ancientreligions#161]
hold_tristeria decision exists in two files:
 - ACR_society_decisions.txt, line 875
 - ACR_hellenic_decisions.txt, line 818

**Comment by xirsoi** [comment]
Thanks. Tristeria is an in-dev feature and I haven't completely decided how it will work. Didn't realize I had duped the *name* though. Thanks!

**Comment by IhateTrains** [comment]
Could you make me a Collaborator? I have some fixes for you :)

**Comment by xirsoi** [comment]
I did make you a collaborator, it's waiting on you to accept.

**Comment by IhateTrains** [comment]
Oh, sorry, I didn't receive the usual notification. Thanks! I will share the first fixes as soon as we release new WtWSMS version :)

**Comment by xirsoi** [comment]
Make a branch and submit a PR to develop.
