### ISSUE TITLE
A more Roman pagan revival path for hellenism

### ISSUE THREAD

**Issue by LithuanianLietuvis** [xirsoi/ancientreligions#168]
in [Mount Summanus](https://en.wikipedia.org/wiki/Summanus) paganism had survived quite long, perhaps we could have a event for a pagan priest like in the Maniot conversion event but for Italians or people of Roman culture? As it is likelly that paganism would have survived there in small groups until the era of Charlemagne.

**Comment by xirsoi** [comment]
Closing this as it really belongs as part of #116 .
