### ISSUE TITLE
Rename druidic to celtic_pagan ?

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#17]
Do you think it would be ok to rename druidic to celtic_pagan and druidic_reformed to celtic_pagan_reformed ?

Pros:
- Both CK2+ and WtWSMS use this as religion key, so that would simplify the integration (no painful / error prone replace in files)
- It seems more inline with vanilla convention xxx_pagan for religions from pagan_group.

Cons:
- Saved games compatibility, would have to be done with a major release.

**Comment by xirsoi** [comment]
Sounds good, but we definitely want to wait for a major release.
I'll make this change when the time comes, since I use SublimeText and can do Find and Replace across an entire folder tree.

**Comment by xirsoi** [comment]
Done in branch feature/celtic_rename. Could use some help testing it, since its so far reaching.
Validator gave it a pass though.

**Comment by xirsoi** [comment]
re-assigning to rquinio, since he's pretty much taken this one over

**Comment by rquinio** [comment]
This is merged to develop
