### ISSUE TITLE
PB/VIET/SWMH compatibility sub-mods

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#18]
Shouldn't these sub-mods be deleted from master for now, to avoid confusion ?
Given the changes in the mods since they were last updated (mid-2013), I assume this would have to be re-done from scratch.

**Comment by xirsoi** [comment]
Yeah, delete them from develop and when we pull to master for the next update they'll go away.

**Comment by xirsoi** [comment]
Done in develop.
