### ISSUE TITLE
Make Pyramids less boring

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#187]

**Comment by secretfire42** [comment]
One of the most common activities around the pyramids was looting of them, both by locals and by descendants. Perhaps you could have a few event chains:

1. Where low-prosperity counties can (for gold) get a massive prosperity boost by utilizing out of work peasantry (or peasantry between harvests/etc.) as temporary laborers on pyramids/temple complexes. The pay for this was traditionally good enough that it was seen as a very enviable job, equivalent to government work today. 

2. There could be random events with peasantry/nobles/distant relatives robbing from your ancestors tombs, and you'd have to decide not only punishment, but how to discourage it. Obviously you might make different decisions for peasantry robbing it (the Egyptian methods varied from curses, harsh punishments, guards, to building new cities and temples to house dedicated workers and/or guards in) - then from the nobility. If a powerful vassal loots a pyramid, it might mean war.

3. Likewise, when you die, your children could get an event pop-up letting them loot your pyramid/tomb, ranging from just taking the gold and reburying you, to wholesale looting. Obviously this would encourage others to do it as well, and lower moral authority, but if your death caused an expensive civil war, it might be attractive.

**Comment by xirsoi** [comment]
Essentially fixed by vanilla, as the Great Works feature is better.
