### ISSUE TITLE
Immortality Event Chain Hellenic Bugs

### ISSUE THREAD

**Issue by secretfire42** [xirsoi/ancientreligions#188]
Current Behavior: It looks like the immortality event chain was changed to add in hellenic pagan courtiers as Eternal Life Mystics. Unfortunately, something about how this was done causes them to be generated in ways that ensure they have different characteristics to whatever category of mystic they are supposed to be making; the young female norse mystic comes out as one of a million varieties of age and gender, for example - and in general, they no longer match their descriptions at all. 

Expected: Female mystics should still be female. Old/young mystics should still be old or young, as appropriate.

**Comment by xirsoi** [comment]
Each of the mystics will appear as one of at least two random options, three for a couple of them. I'll look at modifying the event text to match the generated mystic.

**Comment by xirsoi** [comment]
Basically fixed, improvements will be made over time.
