### ISSUE TITLE
Lack of Celtic Societies Driving Up Secret Christians

### ISSUE THREAD

**Issue by secretfire42** [xirsoi/ancientreligions#189]
Current: Because the only societies Celts can join are the Unseelie court (only if they have 'sinful' traits) or Secret Christians, in practice almost all characters without bad traits become Secret Catholics, seemingly out of sheer boredom. Wait a few decades and look around in debug and you'll see virtually everyone is a secret catholic.

Expected: Paradox solved this a few patches back by tinkering with the society code, and by putting in at least one society alternative for every religion. Perhaps make a Celtic version of the Martial Orders?

**Comment by xirsoi** [comment]
Making Warrior Lodges for ancient religions is next on my list.

I also have some monastic societies planned for most of the religions

**Comment by xirsoi** [comment]
I consider this ticket essentially completed with the creation of warrior societies.

More societies will eventually be created too.
