### ISSUE TITLE
CoAs and Flags

### ISSUE THREAD

**Issue by jbelig** [xirsoi/ancientreligions#19]
Quick review:
I already have decent sets for Celtic and Hellenic and will create Egyptian probably within next week (work permitting). I did a quick search and there's plenty of option for egyptians, so won't take long.
My main issue is the frames, especially the map ones. 
Celtic is rather easy, norse graphics work for them.
Egyptians I believe should use the muslim ones. I'm not sure about the character view with that, will check how it looks later.
Now about hellenic... I've already worked with fixing them for using the christian graphics. The map view is a bit meh, the character view is going in a good direction. Again, muslim is an interesting option for the map and I can recustomize the character frame to make it distinct, so I'm open to suggestions.
Here's what I'm working for character view frame (hellenic) right now:
![frame_hellenic](https://cloud.githubusercontent.com/assets/10557393/5790544/14aaae62-9ea6-11e4-8881-62364ef998bd.jpg)

**Comment by rquinio** [comment]
Hi jbelig,

Looks awesome, but I'm not sure if the title shield frame in character view are actually moddable per religion... :/
It seems hardcoded per vanilla religion group, in generalstuff.gfx:
````
maskedShieldType = {
		name = "GFX_shield_big_pagan"
		textureFile1 = "gfx\\interface\\shield_big_overlay_pagan.tga"
		textureFile2 = "gfx\\interface\\shield_big_mask_pagan.tga"
		effectFile = "gfx/FX/maskedflag.lua"
		clicksound = generic_click_04
	}
````

For the map ones, it is based on graphical_cultureof the religion set in ACR_ancient_religions.txt:
- hellenic_pagan = westerngfx
- druidic = norsegfx
- egyptian_pagan = africangfx
New stuff seems modable via mapitems.gfx, but would need to be tested:
````
EMFXActorType = {
		name = "norsegfx_count_shield"
		actorfile = "gfx\models\Shields\norse_count_shield.xac"
		scale = 0.27f
		use_animation = no
}
````

**Comment by jbelig** [comment]
Yeah, I'm aware of those files but it seems that they all refer to a frame.dds file. I've got it working in game already and it changes all relevant icons. Diplomacy screen, claims etc. I created a new type in coat_of_arms.gfx so that this frame doesn't apply to other religions.
What I cannot change, is the wooden pagan background and related things like the green circle on strong claim icon. The only way to change that would be to move hellenic out of the pagan group, which is an idea worth considering in fact. Apart from the graphical issues, it is a pre-reformed religion and it seems right that they would view other pagans as barbarians. Maybe with exceptions for egyptians and zunists. Not sure what problems would be caused by creating a new religion group though.

**Comment by jbelig** [comment]
On a side note, I tested the zoroastrian layout and though on map the frame looks rather fitting, the interface with the green and muslim-style decorated buttons look odd for hellenism. 
Still would be fine for egyptians though

**Comment by jbelig** [comment]
Here's how it looks in game:
![2015-01-18_00001](https://cloud.githubusercontent.com/assets/10557393/5790733/35b9fba4-9eaf-11e4-8abe-87857ca38bbd.jpg)
![2015-01-18_00002](https://cloud.githubusercontent.com/assets/10557393/5790734/3d59a5a8-9eaf-11e4-9c3d-4b2bff2cdd83.jpg)
In the second image, notice the black area on the coa of Sozopolis? That's a vanilla coa, I've fixed this issue for my own. It seems that the same problem goes for christian and pagan vanilla custom coas. It's not easily noticeable, cause most provinces have their own flags and don't use custom ones.

**Comment by rquinio** [comment]
Ok, I didn't know this was possible !

I don't know if there are any hardcoded features/behaviors in pagan_group useful for pre-reformed religions. I remember in the old forum thread that superskierpat tried it for hellenic_pagan but finally gave up.

**Comment by xirsoi** [comment]
I've been considering moving hellenic and kemetic out of the pagan_group, since it doesn't really offer anything for them (except being the target of missionaries and pagan subjugations cbs). Super was considering moving them into the Zoroastrian Group and changing its (the group's) localisation to "Classical Religions." schwarherz has warned me against it, believing it to be too confusing. I'd deferred to his greater experience for now, but thought I should mention it.

jbelig, I like that frame quite a bit! It seems slightly flat though, could you add an outline to the inner part of the frame? It would help make the actual CoA stand out more.

Also, would you consider making the CoA's look like banners? I have no idea how that would work, but I feel like it would look great with the columns and leaves.

**Comment by jbelig** [comment]
Well, I could try moving the religions to a different group and see how it works while you work on other things. I have no idea about the missionaries, but I believe the pagan subjugation cb can be easily fixed.
About the coa, I will explain my issues in a separate post in a while, got to run right now.

**Comment by schwarherz** [comment]
To be completely fair, there is no reason you couldn't make an ancient_pagan_group or something like that which operates independently of the pagan_group or the zoroastrian_group. The only potential issue I can see is I don't think there's a way to give the new group access to the pagan gui (with the holy site displays), I THINK new groups default to the christian GUI, though I could be mistaken on both counts.

**Comment by schwarherz** [comment]
I would like to say though: these look REALLY good, do you mind if CK2Plus uses them as well?

**Comment by jbelig** [comment]
Here's what's going on with CoAs.
The default mask is this:
![plain](https://cloud.githubusercontent.com/assets/10557393/5791849/40cdeef2-9efe-11e4-843c-60f32a24f2dd.jpg)
If it stays like that, you'll get the black area that you see in Sozopolis (some posts above) on the map coa, but the character coa will be fine. To cover that black thingy, I changed it to this:
![plain_hellenic](https://cloud.githubusercontent.com/assets/10557393/5791853/782eba0c-9efe-11e4-88fb-9e4c760fe83e.jpg)
Now, the default frame is:
![frame](https://cloud.githubusercontent.com/assets/10557393/5791854/87b460bc-9efe-11e4-9c7b-0df9ee6bc2f5.jpg)
This is smaller than the mask, which means the background colour of the coa exceeds the limits of the frame and it looks very ugly.
I enlarged the frame, and it resulted in some clipping at the edges so I thought I'd cover it up with the columns and the wreath.
So, my frame now is precisely at the limits of the drawing area. If I want to put an outer design to make it banner like, I'll have to reduce the size of the frame, while I cannot reduce the size of the inside mask (cause it will mess my map coas again). This might make the coa emblems clip under the frame. 
Same thing more or less goes for the inside outliner though I do agree something is needed there. 
 Having said all that, it's not exactly finished yet so I will try how your suggestion work.

**Comment by jbelig** [comment]
By the way, the same problem exists for celtic coas as well, so I was currently working on a similar workaround for them. This is what I got so far, though it's wip and I'm looking for better options:
![frame_celtic](https://cloud.githubusercontent.com/assets/10557393/5791884/56800562-9f00-11e4-9087-570f24b6a6e1.jpg)

**Comment by jbelig** [comment]
Schwarherz, thank you for your comment. I have no problem if you use it as long as stormweaver is ok with it.
What you say about new religion groups makes sense, so I'm tending to vote for moving them into the zoroastrian. Are the zunists already there? I suppose they should also be at the same.

**Comment by xirsoi** [comment]
If its going to be a pain, don't worry about it.
Zunists are in the Pagan Group, which makes sense, because they have a reformation.

**Comment by jbelig** [comment]
I've done some more work on hellenic frame. Couldn't find a decent way to make it banner-like I'm afraid, but I tried to make the coa stand out of the frame a bit. I enhanced the vanilla lens effect which makes it look a bit more 3d. Also, I sharpened the frame so the lines are clearer. Here's what I got now, hope you can see the differences:
![2015-01-18_00003](https://cloud.githubusercontent.com/assets/10557393/5794137/886f1f04-9f69-11e4-9c97-de43e240953e.jpg)

**Comment by jbelig** [comment]
I also looked at the interface graphics for different religion groups and it seems it's easy to customize them. I figured that since the idea is to have zoro, egyptian and hellenic in the same group, there's no need to make a new since we have the zoro template ready. I already tried to move hellenic there and the only problem was that I was getting the decisions for restoring the zoro high church, but that should be easy to fix as well.
Anyway, I'll try to customize zoro interface to fit the other 2 inside as well. I do need a couple of ideas though.
First issue is the symbol for religion tab/piety. Currently it's this one:
![topbar_folder_religion](https://cloud.githubusercontent.com/assets/10557393/5794160/d209864e-9f6a-11e4-8fab-c9d2eec86f64.jpg)
I need a more universal symbol.
Second is the colour of the buttons. Currently they're green (see image again). Could change them to default christian blueish, but I was thinking something more silver or probably better gold.

**Comment by xirsoi** [comment]
I'm going to open a new issue to discuss moving Hellenic and Kemetic into a different religion group.

I'm liking your progress so far, its looking great! One thing though, the CoA's themselves look like they are using a lower resolution than the frames and the vanilla CoAs.

**Comment by jbelig** [comment]
Actually I had to reduce the resolution of most of them to make it the same with the default ones (72 ppi). I wanted to try to leave them at something like 300ppi and see if the game will adjust them properly, thanks for reminding. 
Also, most of the hellenic ones came from ancient statues, wall paintings, amphoras. What I had to do is change their actual colours to plain red, green, blue so that they'll work with the customizer colour picker. Some of them came off a little 'cloudy' after that procedure and I intend to either fix or get rid of those ones.

**Comment by jbelig** [comment]
Just for comparison, here's the current full hellenic set and one of the vanilla coa sets:

![hellenic_pack](https://cloud.githubusercontent.com/assets/10557393/5796873/9513fb40-9fb8-11e4-95a4-f5984116348a.jpg)

![pattern4](https://cloud.githubusercontent.com/assets/10557393/5796880/b20bd538-9fb8-11e4-8808-97ca9f0ff184.jpg)

**Comment by xirsoi** [comment]
jbelig, those look great.
I noticed in generalstuff.gfx that it references several different sizes for frames and shields (small, medium, and big). Could that be part of your alignment issues?

Also, I would recommend talking to Arko and/or AnaxXiphos to see if they have any ideas. They *are* pretty much the modding communities resident experts on the graphical side of things.

**Comment by jbelig** [comment]
Yeah, I've seen the different sizes in this file and I still haven't figured out why they're there. It seems that the frame.dds and plain.tga files that exist in gfx/coats_of_arms do all the job. Perhaps if I modify the other files they will override those now that I think of it, so I'm going to try that.
I haven't been able to do anything the past couple of days due to work, but I will probably have some free time from this afternoon on.
I have already asked Arko by the way, he gave an idea that didn't work for me but I suspect that he didn't understand exactly what my issue was. That said, I know that in his pack he did exactly the same work for the round pagan coas that have the same problem.

**Comment by jbelig** [comment]
I just tried tweaking the files that generalstuff.gfx refers to. They define the sizes for normal flags, not coas.
That gave me an idea though. After I'm done with all coas, I'll make some fixed flags for select provinces if they happen to turn hellenic (or celtic or whatever). 
Now I was thinking, what I'm doing here will raise compatibility issues with other mods and it will increase the size of the mod download quite a bit. Do you think I should build that as an optional sub-mod instead of including it in the standard download?

**Comment by rquinio** [comment]
What kind of compatibility issues ?
For changing the flag of a title dynamically, there is this new set_coa command which might be useful:
````
k_italy = {
  set_coa = k_lombardy
}
````

**Comment by jbelig** [comment]
Well, I basically had ARKOpack in mind cause I always play with that. On second thought it's not really important though, since we're going to mess this up anyway if we change religious groups

**Comment by xirsoi** [comment]
*If* we change the religion groups. We still don't know if its the best idea.

**Comment by jbelig** [comment]
I know, I know

**Comment by jbelig** [comment]
I've spent the last couple of days polishing the hellenic coas. I've replaced some, doubled resolution and fixed some others. So here's the final version since I've reached the limits of my graphic potential...

![hellenic_pack](https://cloud.githubusercontent.com/assets/10557393/5889371/d63b845a-a42a-11e4-87b7-4380785c45c8.jpg)

**Comment by xirsoi** [comment]
They're gorgeous, good work :+1:

**Comment by jbelig** [comment]
I'm almost done with egyptian coas. All I need to do is resize and tweak them, and I really need an opinion for that. Are we going to use africangfx as ck2+ or change it to muslimgfx? Here they are for a quick comparison. Note that the coas on screens are the default ones and that the black circle you see in africangfx screen will be fixed anyway.

![2015-01-28_00001](https://cloud.githubusercontent.com/assets/10557393/5934106/08f92686-a6d3-11e4-812b-dbf6bf6bf80a.jpg)

![2015-01-28_00002](https://cloud.githubusercontent.com/assets/10557393/5934110/119d3430-a6d3-11e4-99fe-0be9b5775333.jpg)

Another small note. The horses on africangfx empire border are not really unfitting for ancient egyptians, since they had chariot archers as their signature military unit.

**Comment by jbelig** [comment]
Still need a lot of work (see previous post), but here's a preview of the Kemetic pack:

![kemetic_pack](https://cloud.githubusercontent.com/assets/10557393/5938575/fa73df48-a704-11e4-9062-81765eeb5922.jpg)

**Comment by rquinio** [comment]
For the map (i.e. religion graphical_culture), I'd say africangfx to easily differentiate pagans from muslims.
For the other screens which template will you use as basis ? The pagan round/plain one ?

**Comment by rquinio** [comment]
Btw, both patterns look awesome :)

**Comment by jbelig** [comment]
Well, either way I'll have to go with a round template, both muslim and pagan use that one. I was thinking of using the muslim frame for the other screens (hexagonal), but I have to see how the image will fit in once I scale it in order to fix the black circle.
Africangfx does indeed stand out in this area of the map, and it's my favourite frame generally, but personally I lean towards the muslim for this one. The decoration seems more fitting. One vote remaining I guess :)

**Comment by jbelig** [comment]
And since we're on a voting procedure, what do you think of this celtic frame?

![2015-01-28_00005](https://cloud.githubusercontent.com/assets/10557393/5943220/c12d829a-a725-11e4-9e7a-c3e4dcea2384.jpg)

I'd also like a final opinion about the hellenic frame I've made (scroll a bit above). Though I loved it at first, I'm having second thoughts that it might be too much.

**Comment by xirsoi** [comment]
I like the Celtic frame, but I also liked the old green one. I think this one will contrast better with all the green CoAs we'll be seeing though.

I prefer the African frame over the Muslim one for Egyptian Pagan.

I'm tending to agree on the Hellenic CoA being a bit much, now that I've been looking at it for a while. I really like the laurel on the bottom, but perhaps you could do something different with the sides and top?

**Comment by jbelig** [comment]
African it is then! 
I like the laurel too, so I've already reworked it to this one:

![frame_hellenic](https://cloud.githubusercontent.com/assets/10557393/5950037/6bdec6fe-a75d-11e4-985b-b7c5bfd01e68.jpg)

Regarding the celtic frame, I have a fear that it might also be a bit much so there's the option without the corners:

![frame_celtic12](https://cloud.githubusercontent.com/assets/10557393/5950044/8e07c5d2-a75d-11e4-99e2-83ecb8870721.jpg)

**Comment by rquinio** [comment]
Perfect for Hellenic !
Yeah, I agree the squarish Celtic frame looks a bit heavy, a more circular shape fits better.
I don't know if snake symbol could fit ?
![snake](https://cloud.githubusercontent.com/assets/1886883/5957549/2f51d63c-a7bb-11e4-929b-c8f7eaa9e058.jpg)
Also I liked the original greenish CoA you did too :)

**Comment by jbelig** [comment]
Ah, ouroboros. This one is actually universal. I've found the specific image in norse, celtic, egyptian and hellenic pages... In fact, I was considering it for kemetic.

**Comment by jbelig** [comment]
Ok, I tried the green celtic frame again and it doesn't work. I need something more solid to cover the colour of the coa that exceeds the original frame. I did something else though that I like quite a bit:

![2015-01-29_00008](https://cloud.githubusercontent.com/assets/10557393/5965827/c35e3e0a-a807-11e4-9fd0-89e0e225ce99.jpg)

I like that it blends well into the original frame while still giving a clear celtic feel.
Now the kemetic, it's going to be a real pain...

**Comment by jbelig** [comment]
Now that I see the image here, it looks a bit off, but that's not the case in game. On the upper side of the circular old frame, there's a brown lining which is from the original. On the lower side, this line is much darker and not quite visible here. If you see the whole thing in game it looks as one piece.

**Comment by jbelig** [comment]
Well, that was a lot quicker than I expected. I came up with a kemetic frame, which is from an actual ancient egyptian tombstone. In full resolution you can see the hieroglyphics on it, but not at the game size and res I'm afraid. Anyway, here it is:

![2015-01-29_00014](https://cloud.githubusercontent.com/assets/10557393/5966782/f34a28d8-a80f-11e4-8c64-5ab103b60a76.jpg)

**Comment by rquinio** [comment]
I like it !

**Comment by xirsoi** [comment]
As do I!

As for the Celtic frame, I prefer the gold chain look you had before.

**Comment by jbelig** [comment]
I can try a compromise, the gold chain with just the upper corners maybe, see how it looks. 
The one with the 4 corners is a bit heavy in game, especially on screens were you get lots of them in line.

**Comment by xirsoi** [comment]
Actually, the thing I like the least about your newest Celtic frame is that its top heavy. Could you show us what it looks like to have several of the "cornered chain" frames in a row? In game I mean.

**Comment by jbelig** [comment]
Sure thing, here it is:

![2015-01-30_00001](https://cloud.githubusercontent.com/assets/10557393/5971804/526c93b4-a856-11e4-8dde-7b62082853d7.jpg)

And here's why it had to be top heavy. When I resize the mask to make it fit better in the map frame I get this 'flooding' colour on other screens (see the red at the top? ). The golden  chain frame solves the issue even without the corners though.

![2015-01-30_00002](https://cloud.githubusercontent.com/assets/10557393/5971812/87a9eeb4-a856-11e4-825d-7d06830d1b44.jpg)

**Comment by xirsoi** [comment]
I can see now how the cornered chain frame is a bit too much.
I prefer the chain frame myself.

**Comment by jbelig** [comment]
All packs are ready. Here's the finished celtic one:

![celtic_pack](https://cloud.githubusercontent.com/assets/10557393/5990536/1ad3710c-a9be-11e4-8ecc-455b3ec01e30.jpg)

Since I still can't fix stuff on github, I'll email them tomorrow in a zip with all folders arranged. I'm altering 2 files that are already in the mod, ACR_ancient_religions.txt and coat_of_arms.txt. Are there any recent alterations to those files? Should I just get the ones from develop branch and modify them? I'll probably fix the whole thing early tomorrow since it's 3 AM here already and I have a work appointment in the morning (no Sundays for me... )

**Comment by jbelig** [comment]
Forgot to mention that I'm going with the golden chain celtic frame for now. If I come up with a better idea later, it's just one little file.

**Comment by xirsoi** [comment]
If its not too late, please use the latest develop branch.

**Comment by jbelig** [comment]
I was merging my coas and came across an unexpected problem. It seems that has_coa_on_barony_only=no is referring to whole groups only and not separate religions.
The default for pagan group is yes and if I set it to no in our own religions file it changes coas for all pagan provinces in game and gives them random ones. 
That alone can be an issue for some players if they prefer to use specific flags, but also causes the nasty black circles to appear on map (this can be fixed though with only a couple additional tga files).
On the other hand, I'd hate to see my coas used only for dynasties and have provinces keep their old christian or muslim ones. It does look awkward to be a hellenic byzantine emperor with Zeus as your dynasty emblem and the cross as your realm flag...
I tried to set a different value for each pagan religion but it didn't work, so it's either all random coas or all fixed flags. Opinions? Votes?

**Comment by rquinio** [comment]
Well that's one more reason to move Hellenic & Kemetic out of the pagan group !
I confirm has_coa_on_barony_only only works at religion group level, it's a mess....

For now I would say keep has_coa_on_barony_only = yes on pagan_group, because other pagans would lack random/quality patterns.

**Comment by jbelig** [comment]
Well, I could make patterns for others pagans as well, but that would exceed the scope of the mod quite a bit  :P
You do have a good point there, but again on the other hand when people play ACR they will choose one of our 3 religions. So I'd say let's make those 3 look good and blame paradox for the rest?

**Comment by jbelig** [comment]
I mean, just compare the 2 images. I included Bulgaria so that you see what happens to other pagan coas to:

![2015-02-01_00001](https://cloud.githubusercontent.com/assets/10557393/5993945/c0cf63d4-aa6a-11e4-9cff-feeb1fb07865.jpg)

![2015-02-01_00002](https://cloud.githubusercontent.com/assets/10557393/5993946/ca63e9d8-aa6a-11e4-9fb8-502dba80b919.jpg)

**Comment by rquinio** [comment]
Good point, let's make it best for mod users ! The cross is indeed a bit immersion breaking :)

**Comment by jbelig** [comment]
Ok, now that I'm done with those do you have in mind any other way I can help?
I still can't work github properly but that will probably be fixed within a couple of weeks when I'll have my second computer set with windows 7.
Also, I'm not a coder. All my previous 'modding' work was to take stuff someone else did and change it to suit my taste. I doubt I could create something from scratch like you guys do.
Anything in mind that fits my -limited- skills?

**Comment by xirsoi** [comment]
Well, you are pretty amazing at graphics, thats for sure. I know I have need for at least one event picture, and I imagine we'll need more in the future.

As far as code goes, I'm not sure. If an issue is created that piques your interest and no one has taken it for themselves you are free to assign it to yourself.

**Comment by jbelig** [comment]
Which event is that then?
Also, I found a little bug. Sacred dogs second modifier doesn't work (garrison_growth - wiki says it was broken in 2.2.1). As it's tiny, I can use this to learn how to do stuff properly on github. So, I forked the whole thing to my account. Can't create an image on my pc, but I can edit this online. If I got this right, I fix the error and then I send a pull request?

**Comment by xirsoi** [comment]
I require an event picture for the Titan Thysia, to replace the viking blot event picture. Someone chained to a stone altar in front of a temple and about to be sacrificed by a priest with a dagger. The "painterly" look of the vanilla event pictures, or greek pottery, or the renaissance look of the other ancient religions event pics would be fine, i'm not picky. I just don't want to use the blot pic of people hanging from trees in front of a long house in the middle of winter.

What is "Sacred dogs"?

**Comment by jbelig** [comment]
It's one of the sacred symbols province modifiers (sacred_carnac, sacred_stonehedge, sacred_bear, sacred_lake, you get the picture)

**Comment by xirsoi** [comment]
boom, done!
