### ISSUE TITLE
Too much in Celtic doctrine - and devolution of egyptian paganism

### ISSUE THREAD

**Issue by developer000** [xirsoi/ancientreligions#196]
I'm against adding equality/patriarchy/matriarchy to these doctrines - and it's limits possibilities of use such doctrines - also celtic has already heresy which gives matriarchy. Egyptian devolved by removing polygamy and giving concubinage. These doctrines are already big without unnecessary adding of equality to both of these.

**Comment by xirsoi** [comment]
Animism and Stability are very minor features, and Equality is something inherent to both of the unreformed religions.

Also, Polygamy doesn't work for women, so changing it to concubinage is the only way to make it work.

**Comment by developer000** [comment]
and Equality is something inherent to both of the unreformed religions. - so YOU CLAIM. like where did you see a female pharaoh - Of course you had some women who had great power and few regents - but that is not reason to give equality [if it was then we would have equality in taoism] - thats normal ck2 inheritance law - low patriarchy. Equality was not inherent to Ancient egyptian religion - yeah women had little more laws but thats not at level on bon or afrian(west).
Also, Polygamy doesn't work for women, so changing it to concubinage is the only way to make it work. - so don't give equality - it will work then.
Animism and Stability are very minor features - look at slavic/baltic/finnic religions - thats enough
also you are forgeting army modifiers.
I'm against forcing player to equality with this.
Also just because some feature in small quantity does not mean we should give all qualities there - why they get polyandry .....  for fsck sake.

**Comment by xirsoi** [comment]
In ancient Egypt there were laws that protected women's right to hold property and they had equal rights in inheritance. Compared to almost every other society of that era, hell even in the game's time frame, that's practically egalitarian. There are several instances of female pharaohs in Egyptian history and they're legitimacy was *never* called into question on account of their gender. NEVER.

Players are not forced to do anything, they can choose any combination of features they want. If I remove anything from these doctrines, it's going to be the army modifiers.
