### ISSUE TITLE
Brittanics get no title/bloodline when forming Pyrdain

### ISSUE THREAD

**Issue by secretfire42** [xirsoi/ancientreligions#203]
As per title. Old Celtics or reformed Druidics get the traditional Welsh Savior  honorific equivalent to "Y Mab Darogan" (Pendragon) - but Brittanics do not. I think this is a bug, as I'm not sure theres a valid reason for them not to get it too, especially with historic figures such as: https://en.wikipedia.org/wiki/Gwenllian_ferch_Gruffydd being venerated for as long as they were. Or at the least, some other form of bloodline (like descent from Boudica, or Morganna or somesuch.)

**Comment by secretfire42** [comment]
I think a big part of the issue is that the event just isn't set to fire for them. But even if you mod it in, the "religion_openly_celtic_or_reformed_trigger" doesn't take them into account. I was able to do the former, but for the life of me I can't find where that trigger is set, at all. Its not in the modded scripted triggers file...that I see, at least.

**Comment by xirsoi** [comment]
fixed on develop
