### ISSUE TITLE
Post-Great Works Kemeticism Almost Impossible to Reform

### ISSUE THREAD

**Issue by secretfire42** [xirsoi/ancientreligions#206]
After the 'great works' stuff, there's no longer (as far as I can tell) any options to rebuild various parts of the priesthood or to build a pyramid. This has made Kemeticism virtually impossible to reform. I had become Emperor of the /entire Arabian Empire/ but still could not reform it as there was no plausible way to root out the arabic priests without the ability to either get up moral authority or to demand conversion.

**Comment by secretfire42** [comment]
Edit: Might be wrong. Restarted and the Asyut decision, at least, appeared as normal. Not sure what was going on.

**Comment by secretfire42** [comment]
Okay, so after about ~10 hours playtesting this again, //unless I am derping very hard// everything works except...I can't figure out if there's still a command at all to build a pyramid, since I'm assuming thats been superceeded by the Great Works thing. I can see pyramind BUILDINGS appearing as an unbuildable option now, but no decision ever appears. I did eventually manage to get the 'restore the luxor' decision to pop up, but....when it completed, the event chain finished as normal, but did the old bug where it would make a new empty holding and a title, but not an actual building, resulting in the game giving a perpetual 'wrong holding' message. I think its been years since I've seen that one, but I know it was a bug at one point.

Also, grats on the patreon!

**Comment by xirsoi** [comment]
I could have sworn that I responded to this ticket, I'm really sorry I didn't.
Not a good way to treat your first/only patron 👎 

Restore Luxor is only supposed to create a new temple holding and a temporary boost to moral authority. I've considered having some kind of unique building as well, but unique buildings are a serious performance issue (so i've been told).

Thank you for being my first supporter! I didn't expect it to be you, but I'm not surprised. You've always been my most awesome fan.
