### ISSUE TITLE
Bug: Crash - Kemetic Reform Crashes the Game

### ISSUE THREAD

**Issue by secretfire42** [xirsoi/ancientreligions#211]
As per title. I disabled all other mods and started a 'test game' and just cheated my way to reform really quickly in the viking start to test it. Upon selecting any doctrines (even if its not Children of the Nile) - clicking reform crashes the game. Not sure why; poked around but got no ideas.

**Comment by xirsoi** [comment]
Thanks for the report!

This bug was fixed in the Pryderi update.
