### ISSUE TITLE
Greco-Egyptian Religion

### ISSUE THREAD

**Issue by jbelig** [xirsoi/ancientreligions#23]
I was reading some stuff about hellenic religion during roman age and it reminded me that at this time they added a few egyptian and syrian god into their pantheon. Specifically, Isis and Serapis from egypt. I was thinking what possibilities could this open. 
Perhaps a system like orthodox-iconoclasts. You'll have some who remain true to the old Olympian gods and the others (probably the majority at that time) who combine them with roman and egyptian deities.
Or something much more ambitious, a decision similar to the schism mending for hellenic and kemetic? I don't have this quite clear in my mind yet, but the main idea is to combine the 2 beliefs (maybe leave the old ones as heresies). You could do that if you control all italy, greece and egypt I suppose. I understand this could be a real pain to implement, but I find it very intriguing.
Thoughts?

**Comment by xirsoi** [comment]
Perhaps a sort of religious melting pot...

**Comment by jbelig** [comment]
Something like that, though I don't think the old religions should disappear, just become heresies. 
That's what orthodox-iconoclast system does and I believe same happens after mending the schism?

**Comment by xirsoi** [comment]
Technically, any heresy can make usurp its parent's place as the dominant religion. The heresy must have a high religious authority and have at least 5 more provinces than the parent.

**Comment by jbelig** [comment]
Ok, first of all sorry for not being able to help at all for so long. I finally found some free time and I was thinking what kind of game I should try and came up with an idea that got me really motivated and doesn't sound hard to fix with my limited modding knowledge.
The theme is the restoration of the empire of Alexander the Great and it's rather easy to make because it will follow the same basic principles of the vanilla restoration of Rome (founding, then trying to restore borders, then maybe an ambition to go even further than Alexander). So it's just modifying events and adding proper localization to make it functional, something I can definitely do.
I think this will add an interesting alternative for hellenic games in case someone doesn't like the Roman route. As I see it, if you go Roman you deal with orthodox and catholics, if you go Macedonian you deal with orthodox and muslims.
What do you think about it? Is it something you'd like to implement in the mod?

**Comment by xirsoi** [comment]
I dig the idea of Macedonian flavor! I've had several people on the forums and in the Workshop say that they want more support for Greek style Hellenism. I'm still not entirely sold on a Kemetic-Hellenic hybrid religion, but a restoration of Alexander's Macedonian Empire sounds great!

**Comment by jbelig** [comment]
You're probably right about the Kemetic-Hellenic hybrid. Alexander's conquests led to several religious 'melting pots' anyway. Perhaps there can be some events that say you're impressed by the figure of the goddess Isis or/and the teachings of Zarathurstra, Buddha etc and create cults?
I was thinking that a high level of tolerance maybe should be a condition to revive the empire (not sure if it should be called hellenic or makedonian, will look into it). Is it possible to tie the creation to realm laws?
Also, you said elsewhere that we can't have cultural localization? Does this mean that I can't change the name of the Pontificate to something more greek if someone goes the Alexander route instead of Roman?

**Comment by jbelig** [comment]
Maybe we could have 'emulate Alexander' trait as well and make that a condition for reviving the empire?

**Comment by jbelig** [comment]
I have a problem. Can you tell me why this event is not firing? It's a copy of the roman province events, just changed conditions and added localisation.

# Eparchy Thrake
narrative_event = {
	id = HEE.2
	title = EVTNAMEHEE.2
	desc = EVTDESCHEE.2
	
	picture = GFX_evt_victory_arch_byzantine
	
	ai = no
	
	trigger = {
		religion = hellenic_pagan
		has_landed_title = e_hellenic_empire
				
		NOT = { has_global_flag = eparchy_thrake }
		completely_controls = d_thrace
		completely_controls = d_karvuna
		completely_controls = d_turnovo
	}
	
	mean_time_to_happen = {
		days = 1
	}
	
	option = {
		name = EVTOPTAHEE.1
		set_global_flag = eparchy_thrake
		prestige = 100
	}
}

**Comment by rquinio** [comment]
Event looks OK. Is e_hellenic_empire properly defined ?

**Comment by jbelig** [comment]
decisions = {
	restore_macedonian_empire = {
		is_high_prio = yes
		potential = {
			age = 16
			prisoner = no
			NOT = { trait = incapable }
			NOT = { has_global_flag = macedonian_empire_restored }
			culture = greek
			has_landed_title = k_byzantium
			religion = hellenic_pagan
			has_character_flag = flag_alexander_way
		}
		allow = {
			prestige = 3000
			completely_controls = d_dyrrachion
			completely_controls = d_thessalonika
		}
		effect = {
			set_global_flag = macedonian_empire_restored
			narrative_event = { id = HEE.020 tooltip = EVTTOOLTIPHEE.020 }
		}
		ai_will_do = {
			factor = 1
		}
	}
}

**Comment by jbelig** [comment]
# The Restoration of Hellenic Empire
narrative_event = {
	id = HEE.020
	title = EVTNAMEHEE.020
	desc = EVTDESCHEE.020
	
	picture = GFX_evt_rome_restored_byzantine
	
	is_triggered_only = yes
	
	option = {
		name = EVTOPTAHEE.20
		hidden_tooltip = {
			primary_title = {
				any_direct_de_jure_vassal_title = {
					de_jure_liege = e_macedonian_empire
				}
			}
		}
		e_macedonian_empire = {
			grant_title = ROOT
			copy_title_laws = k_byzantium
			copy_title_history = k_byzantium
		}
		give_nickname = nick_the_megas
	}	
}

**Comment by jbelig** [comment]
Changed the name to macedonian instead of hellenic and changed the conditions to only 2 duchies so I can check it in game easily. You see anything wrong with those?

**Comment by rquinio** [comment]
Issue could be linked to some non-breakable spaces instead of normal spaces. 
If you copy/paste code on github don't forget to use code blocks (3 times ` character).
But there's also a more efficient way to review code: you can push your WIP code to a dedicated branch on the repo (ex: feature/#23-macedonian-empire) !

**Comment by jbelig** [comment]
I was afraid it might be something like that...
Is there any tool to check non-breakable spaces?
What do you mean code blocks? Don't forget, I'm a total newbie on github :p 
I'm expecting to get my new pc near the end of next week though, so I'll get rid of winxp and I'll setup github properly there.

**Comment by xirsoi** [comment]
Greco-Egyptian religion is half-implemented in Project Augustus, and the feature has been offered for use in AR.

Figure out how it should be integrated (heresy? standalone pagan faith? some kind of wacky melting pot?).

**Comment by xirsoi** [comment]
I have no real desire to do this, so i'm closing for now.
