### ISSUE TITLE
Hellenic religious definitions

### ISSUE THREAD

**Issue by jbelig** [xirsoi/ancientreligions#26]
I was checking the definitions in religions file and I think they need some discussion, probably for the other other religions as well. Anyway, here's my opinions about the hellenic ones (based on my knowledge of ancient greek customs, I don't know much about the romans:

priests can marry - yes. In fact priests weren't permanent, they were assigned by a draw usually every year and anyone could become one. Basically, everyone had rights to perform rituals and the head of the family was the family's priest, but that's not something we can put in game.

intermarry - kemetic, zoroastrian for sure. Probably not the other pagans

female temple holders - yes. Plenty of priestesses examples.

concubines - maybe. Well, marriage was sacred, but they did have slaves (that one goes for romans too). I'm assuming that some of the slaves had 'special' duties... That said, perhaps we should consider a slavery system for hellenic and kemetic? Is this against game rules? Could be something simple like a modifier, nor a really complex system.

more wives - nah...

river movement - probably not. There weren't any major rivers in Greece so even though their navy was excellent this should probably not exist.

call crusade - yes. Purely for gameplay reasons

feminist - no idea what it does?

allow looting - no idea. There was no organized raiding, but there were pirates often supported by lieges. 

defensive attrition - maybe yes. Will it still work if they move out of pagan group?

peace prestige loss - no

raised vassal opinion loss - yes

dislikes tribal organization - no

incest - debatable. The close one was not allowed normally (same in greece and rome), but it appears widely as a concept in mythology between brother-sister. Also, a widow should often marry her husband's brother and it seem that uncle-niece marriage was commonplace. Not to mention the effect of egyptian cultures during the hellenistic period.

Did I forget any other definitions?

**Comment by rquinio** [comment]
There a full list here: http://www.ckiiwiki.com/Religion_modding :)

**Comment by jbelig** [comment]
Oh dear, there's much more than I thought! I suppose first we have to decide whether they'll move from pagan group and where to, so we'll know which ones are needed and which are default.

**Comment by xirsoi** [comment]
I think we could remove raiding and consorts from hellenism, since that doesn't make a ton of sense for them. Perhaps add the uncle-niece marriages, since that was fairly common (certainly in the mythology, if not terribly so among historical rulers).

I think we should give something to hellenism to compensate for the loss of those features. Not designate heir though, since that had more to do with Roman administration than the hellenic faith.

Looking through the list has given me ideas for the heresies, but I'll put those in the appropriate issues.

**Comment by xirsoi** [comment]
Complete with the Hellenic Heresies feature branch.
