### ISSUE TITLE
Gaulish Culture

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#29]
Keegan King, whose username on the forums i've completely lost track of, provided me with the files for a Gaulish culture.

This issue is to remind me to implement a Gaulish Culture and (maybe) some revival events. Preferably something different from the Roman Cultural revival events.

**Comment by rquinio** [comment]
Is that Gallo-Roman culture (https://en.wikipedia.org/wiki/Gallo-Roman_culture) or some even older culture ?

**Comment by xirsoi** [comment]
Even older, pre-Roman conquest. Proper continental Celtic.

They would neat a cultural retinue and appropriate building as well.

Obviously it wouldn't be the "real" Gaulish culture but a revivalist one that tries to mimic whatever cultural traditions they could glean from old legends and classical documents, mixed with a blend of Insular Celtic. That's how I view the Roman revival as well, except its slightly more plausible since the old Roman culture was much better documented.

**Comment by xirsoi** [comment]
pull request merged into develop

**Comment by rquinio** [comment]
Small question that popped up while [integrating the new version of the mod into WtWSMS](https://github.com/rickinator9/WTWSMS/pull/71): what would be the difference between Gaulish and Gallic culture ?

**Comment by xirsoi** [comment]
There isn't one, its an alternative spelling.

**Comment by xirsoi** [comment]
Do we need to change the name of the culture for compatibility?

**Comment by xirsoi** [comment]
Gaulish temples are called Nemetons ("sacred place").
If culture specific localization keys ever get supported, we can change the names of the Celtic gods to their culture specific variants.

**Comment by xirsoi** [comment]
Take care of cultural localisations for Gaulish and close this ticket.
Gaulish Revival needs to be a separate ticket.

**Comment by xirsoi** [comment]
Complete with #122
