### ISSUE TITLE
Ancient Egyptian Culture

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#30]
It could be fun to revive the ancient Egyptian culture as a Kemetic.
And get a proper Pharaoh name such as Amenhotep or Nefertari !
An issue would be the regnal numbers though: a new Ramses II might be kind of strange...

**Comment by xirsoi** [comment]
I think it only makes sense, since we have Roman and are going to do Gaulish.

Any ideas for how it would go down?

**Comment by jbelig** [comment]
Awesome idea. Maybe we could ahead and create a new graphical culture type as well then? Combine the egyptian faces with some more appropriate beards (hellenic or iberian) and hair?
Man, I wish I could make new hair that looks like ancient egyptian wigs...

**Comment by jbelig** [comment]
By the way, I think I'm going to start working on cemetic coas first and polish celtic ones afterwards so that there will be versions for all even if celtic are not perfect.

**Comment by xirsoi** [comment]
Sounds good.

**Comment by rquinio** [comment]
I computed a list of some Pharaoh's names (from Wikipedia) some time ago, if that may help:
````
male_names = {
			Aahotepre Ahmes Ahmose Akhenaten Amasis Amenemhat Amenemnisu Amenemope Amenhotep Chephren Cheops Dedumose Hakor Hor Hori 
			Inkaef Intef Iuput Kagemni Khafra Khety Khnumhotep Khufu Mentuhotep Minkhaf Neferhotep Neferkare Nefermaat Nepherites 
			Osorkon Prehotep Psusennes Rahotep Ramesses Senusret Seti Sobekhotep Thutmose Userkaf Yakareb
}
female_names = {
			Aat Abar Ahhotep Ahmose Ankhesenpepi Arsinoe Aya Baketwernel Cleopatra Henuttawy Henutsen Henuttawy Hetepheres 
			Iput Iset Isetnofret Karomama Khamerernebty Khentkaus Khuit Kiya Maatkare Meketaten Menhet Meresankh Meritamen Meritites 
			Nefertari Nefertkau Nofret Takhat Takahatenamun Tentamun Tiaa Tiye
}
````

**Comment by rquinio** [comment]
Possible idea for an old_egyptian culture revival event: it could be based around finding some stones like the Rosetta Stone (https://en.wikipedia.org/wiki/Rosetta_Stone) with translations of same texts into ancient Egyptian language, hieroglyphs, and Greek, which maybe some scholars in the realm still understand. 
The texts could allow to learn the language, learn about old traditions, etc.

**Comment by jbelig** [comment]
Nice name list! We'd need some dynasty names as well, right? That will be tougher...
I love the Rosetta Stone idea. 
I was thinking if there should be an alternate way as well that would allow the player to try and force the religion swapping on himself without use of designer and without having to wait for a random event to happen (could be expanded to the other 2 faiths). The idea is a decision to let's say visit the ancient pyramids. During the visit something 'magical' happens (you hear voices, see a light maybe) that urges you to move on. You lose your companions and get lost in there. Then 3 options: 
- You stay lost (die)
- One of your companions finds you and you get out (end of story, nothing else happens)
- Something else finds you (not a running mummy, the spirit of a pharaoh I suppose) and offers you enlightement.
On 3rd option you get some more:
- You chase the spirit away (find your way out as well with a small chance of dying again maybe, or stressed or wounded)
- You listen to the spirit and decide to embrace the old gods.

Yes, I love horror movies and yes, I'm a fan of horror VIET events...

**Comment by xirsoi** [comment]
Creation of the culture is complete.

Now need the revival event.

**Comment by xirsoi** [comment]
Coptic Revival event will have to come later.
