### ISSUE TITLE
Celtic: "no court druid" notification keeps firing

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#32]
I've noticed that the event keeps popping up, even when there is an eligible candidate that is suggested.
I'll have a look.

**Comment by rquinio** [comment]
Hmm, I don't seem to reproduce the issue when firing event ancrel.0153 from console.
I'll close this for now, feel free to re-open if needed.

**Comment by xirsoi** [comment]
I happened to be looking through the code while addressing the education event issues and I think I've spotted the problem. The events only check whether you have a courtier with the title Court Druid, but you can also have a vassal with the title.

**Comment by xirsoi** [comment]
Calling this done.
