### ISSUE TITLE
Promethean/Titan Holy Orders and Flavor

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#33]
Titan Holy Order - The Sickles: Kronos was often associated with Sickles (and scythes). This holy order would "cull" enemies of the faith. They are zealots, devoted to destroying that which the Olympians have built and restoring the Golden Age of the reign of Kronos.

Titan Flavor: The Titan Cult seek to restore the Golden Age of Kronos. According to legend no one had  suffered or toiled, the world was at peace and all lived happily. It was only with the beginning of Jupiter's reign that everything went shitty. Thus, everything the Olympians built must be destroyed. From the ashes of the old, a new more glorious world shall rise. Only by spreading the worship and dominion of the Titans on Earth, and diminishing the same for the Olympians, can their gods have the strength to break their bonds in Tartarus and retake their rightful place.

The Titans have a celebration called the Great Thysia. Quite literally a direct copy of the Great Blot, this event chain allows the ruler to sacrifice prisoners on a stone altar caked with dried blood. (Note: Already implemented with initial release of the heresies.)

Promethean Flavor: Prometheans seek to create the paradise of Plato's Republic. They should be able (and the AI encouraged) to transform themselves into a Republic. They see Prometheus and Epimetheus as the fathers of all humanity; both figuratively for creating them/bestowing the gifts of intelligence and fire, and for literally being their antecedents through Duecalion and Pyrrha, the only humans to survive the great deluge sent by Jupiter to end the Bronze Age of Man. Epimetheus is cast in the most favorable light possible. He isn't simple or foolish, he just has different gifts. He represents creativity and other natural talents. He also provides a lesson, through the tale of his wife Pandora, that we must temper curiosity (a most laudable trait) with wise caution. Prometheans praise intellectual and creative pursuits. Scholastics, Art, Astronomy, Engineering, etc.

For the Prometheans I'm thinking some kind of festival. Different events, such as plays and scientific presentations, could highlight the things important to them. Characters could even try to run their own event (create some art, do a poetry reading, present a scientific discovery/invention), with prestige and piety for something good.

**Comment by jbelig** [comment]
I don't know if there's a way to define fierce 'rivals' for a religion, but if there is these 2 heresies fit the bill. Prometheus, even though a titan himself, sided with Zeus during the great war so the other titans and their followers should hate him. Taking that into account, you've made an excellent job with the 2 heresy concepts being completely opposite.

**Comment by xirsoi** [comment]
Actually, I can create an opinion modifier that causes them to hate each other.

Also, thanks, I've put quite a bit of thought into it.

**Comment by xirsoi** [comment]
A decision to re-build the First Academy, the Promethean religious head.

**Comment by xirsoi** [comment]
Thought up another Promethean Holy Order:
The Men of Steel - While the Men of Iron make up the Military Caste of Promethean society, as taught in Plato's Republic, the Men of Steel represent the very best Iron has to offer. Tempered through years of training and made into the ultimate weapons of the state, these might warriors stand strong to shield the Republic against its enemies and cut down those that stand between the state and the resources and land it requires to thrive.

**Comment by xirsoi** [comment]
@jbelig, could you make two really quick flags for me? One is the alchemical symbol for steel, the other would be two crossed sickles, optionally with blood dripping from them.

Any other details I leave up to you!

**Comment by xirsoi** [comment]
(Alchemical Symbol for steel)[https://www.google.com/search?q=alchemical+steel&safe=off&rlz=1C1GIGM_enUS530US530&espv=2&biw=1680&bih=925&source=lnms&tbm=isch&sa=X&ei=8C0bVZeDK8S1oQTD_4CYCw&ved=0CAYQ_AUoAQ#imgdii=_&imgrc=zFhR8_ovwKymKM%253A%3BGIjo5jEn-C84ZM%3Bhttps%253A%252F%252Fs-media-cache-ak0.pinimg.com%252F236x%252Ffa%252Fa5%252F40%252Ffaa5405b5a4433c81eb09a17df44ee95.jpg%3Bhttps%253A%252F%252Fwww.pinterest.com%252Fsawtoothmetal%252Ftattoos%252F%3B236%3B298]

**Comment by jbelig** [comment]
How do they look for the first one (promethean I guess)? Preference between the two?

![promethean1](https://cloud.githubusercontent.com/assets/10557393/6949758/f854f4fe-d8be-11e4-8dd0-74008a47d2ef.jpg)

![promethean2](https://cloud.githubusercontent.com/assets/10557393/6949765/00fec7f6-d8bf-11e4-83d1-19aea0c28874.jpg)

**Comment by jbelig** [comment]
And the titan samples here. See the differences between them and tell me which you prefer please (if any). The last sample has some blood dripping.

![titan1](https://cloud.githubusercontent.com/assets/10557393/6951547/cc5d1970-d8c4-11e4-867a-9547ec499be2.jpg)

![titan2](https://cloud.githubusercontent.com/assets/10557393/6951551/d3be6548-d8c4-11e4-8e48-3e3eb027f5c6.jpg)

![titan3](https://cloud.githubusercontent.com/assets/10557393/6951556/d896f6a2-d8c4-11e4-8bfd-9d9e609108ca.jpg)

![titan4](https://cloud.githubusercontent.com/assets/10557393/6951557/dcdd2e02-d8c4-11e4-9ce8-b900a3a0d92b.jpg)

**Comment by xirsoi** [comment]
I prefer the second Promethean and the third Titan. Thanks for coming up with options :)

**Comment by xirsoi** [comment]
Although I have more ideas for Promethean and Titan flavor, I'm closing this issue for now.
