### ISSUE TITLE
Can't restore Roman Empire as hellenic_pagan

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#37]
Reproduced, the decision does nothing.

**Comment by rquinio** [comment]
The cause seem to be the re-definition of decision restore_roman_empire from vanilla realm_decisions.txt in a different file ACR_LoR_decisions.txt
The potential and allow block executed are the ones from ACR, but no effect block is executed (neither vanilla nor ACR one), and decision just does nothing.
I tried renaming file to ZZ_ACR_LoR_decisions.txt just in case, but same behavior.

So it seems we need to keep the whole realm_decisions.txt in the mod, like it was before...

**Comment by xirsoi** [comment]
Closed with pull request.
