### ISSUE TITLE
ai_zeal / ai_rationality not working on character modifiers ?

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#43]
I've noticed that Titan cultist had 2 NONE modifiers appearing.
In vanilla ai_zeal / ai_rationality is only used on traits, os not sure if it works in triggered modifiers ?

**Comment by rquinio** [comment]
Btw here is partial table of modifiers per scope: http://www.ckiiwiki.com/Modifiers

**Comment by xirsoi** [comment]
Damn, I'll make a fix tomorrow.

**Comment by xirsoi** [comment]
I've disabled the ai_zeal and ai_rationality modifiers for Titans and Prometheans.
I've left in the combat_rating = 2 and learning = 1, respectively. Adds a little flavor I think. Heresies need a little boost anyway.
