### ISSUE TITLE
Egyptian flavour

### ISSUE THREAD

**Issue by jbelig** [xirsoi/ancientreligions#45]
Hey guys. It seems that I can't (and won't be able for quite some time either) keep up with the work you're doing and my new pc will probably be delayed a bit. Since you haven't touched Egyptian flavour yet, I thought I could work on that. Since I can't use github properly, I'll do it on my pc and when I'm done I can do the merging with the main mod, but be warned that my time is really limited so it will take a while.

**Comment by jbelig** [comment]
I've done some research already and found a lot of sources about ancient egypt and their religion so I have a few ideas. Things I plan on doing (opinions needed here of course):
- Some religious flavour is needed, maybe specific holidays. Also, after restoring the church the pharaoh should be head (so it was) and we could add something like the ck2 coronation which would make him perceived as god. Not sure if he should get a 'semi-god' trait like the hellenic bloodlines and if this should be inherited or if this should stay a modifier or something and just trigger the event when a new pharaoh is up (going to read up on this more). 
- Common events. Right now, being in pagan group, kemetic don't have any feast events and once you're done with the big ones ck2 added (luxor restored, pyramid buit) there is nothing at all to do during peace time. 
- Coming of age. It seems that children were only getting general education and not targeted like you've done for the Celts. I've also read that the coming of age was marked by a circumcision ceremony (which would give prestige/piety). Now this didn't happen at a specific age, but I don't know if it's possible for the game to trigger adulthood by an event and not age?
- Court intrigue - need to read up on this to suggest something
- The Nile. Now this could something random be in the form of a natural disaster, or we could go with season triggered semi-random events. Something like 'this year the floods went high so the crops will be good' - province gets modifiers.
- Add Egyptian empire. It should contain Egypt, Nubia and I'll see what else was part of egypt in its prime. Can this be done with the same mechanism as Roman empire or is this hard-coded? I'd prefer if the game didn't start with a de-jure egyptian empire, but only make this after the creation. 
- Egyptian culture. At the moment egyptian is in arabic group which gives them some muslim attributes which don't quite fit with kemetism (for example, they don't get prestige by marriage). So, after switching religions we could make a new ancient_egyptian culture in its own group and maybe add an ancient_nubian as well. I've tested how muslim portraits work with iberian hair and beards and it looks good (though I'll need to fix some small clipping issues). Also persian clothes seems much more relevant than muslim at least as a temporary solution. In the long run, I'll try to make some new headdresses and my very ambitious goal is to find a way to make them all shave their hair and replace them with the wigs we know. 
I'm sure I'm forgetting something, but baby is awake and I have to take of her now. I need some feedback and ideas on that.

**Comment by rquinio** [comment]
Cool, research/ideas is tougher than actual coding for me :)
Some feedback:
- I remember reading on the forum that Pharaoh was head of church in name, but actually delegated much of his duties to great priests hence the separate head ? I guess both could work anyway.
- Maybe Pharaoh could choose a focused/main patron deity for his reign, at coronation time ? I think I've read somewhere ?...
- adulthood is hardcoded at age 16
- The Nile events sounds great idea !
- Egyptian empire: http://en.wikipedia.org/wiki/New_Kingdom_of_Egypt ?
- Definitely, maybe use Egyptian culture dedicated issue: https://github.com/xirsoi/ancientreligions/issues/30

**Comment by jbelig** [comment]
- Pharaoh: That's what I've found so far as well, but in game terms the only real duty the head of religion has is calling crusades which I feel should be pharaoh's responsibility
- Patron deity: I'll do some research on that one, only thing I know so far as that pharaohs were considered gods. Actually, I believe I read somewhere that they were something like gods in waiting, meaning that people understood their human nature but they were bound to become gods at death, so maybe emulating some deity could work?
- Adulthood: I hate hardcoded stuff... So there's no way to make someone younger than 16 to get rid of regent or be capable of leading armies? I think I've read something like that in a mod but can't remember which one. In any case, circumcision ritual can still be there as flavour (and a nice temporary modifier), maybe at a random time between 12 and 16 or something.
- Empire: I've seen some maps from a different period that have all those areas and a part of Mesopotamia too, will research that more properly. It definitely looks like in-game k_jerusalem should be part of it. I wonder what problems this specific kingdom might cause being only creatable by christians.
- Culture: Sure, all that will go into the relevant issue, was just making a summary here.

Another thing I had in mind is slavery (could be a part of hellenism as well). First of all, I vaguely remember that it was against game policy to allow anything related to slavery? If not, there's 2 ways it can go. The easy one would be in the form of a modifier (for the owner) that just shows that this guy has so many slaves and get some prestige from it. This modifier would change by events that you gift or receive slaves, take slaves after a siege, some of your slaves rebel and escape etc. The hard one would be to actually make game characters into slaves. I don't know how much flexibility we can have on this, but the main idea is to give enslaved characters an effect similar to imprisonment, but at the same time the owner should be able to use them as courtiers and assign jobs like educating children. And of course, gift-siege-escape-rebellion events would be there as well.

**Comment by rquinio** [comment]
About patron deity, Zombies Bane suggested on steam workshop to add [Atenism](https://en.wikipedia.org/wiki/Atenism#Contrast_with_traditional_Egyptian_religion) as an option into the mix: by rejecting all the other gods, the Pharaoh becomes the intermediary between the only god Aten and his people.

**Comment by xirsoi** [comment]
I would say allow it as a decision if the Pharoah's patron god is Aten and is Zealous.

**Comment by xirsoi** [comment]
I'm tweaking Atenism, and would like a flag based on the Aten sundisk: http://en.wikipedia.org/wiki/Atenism#/media/File:Aten.svg

**Comment by xirsoi** [comment]
Also, a similar flag but with a spear, or crossed Khopesh or something, for a Holy Order.

**Comment by jbelig** [comment]
I already have the sundisk in the egyptian coa template, so it's just a matter of properly colouring it.
I think I'll be able to make those by tonight or tomorrow morning.

**Comment by jbelig** [comment]
What do you think about those 2?

![aten3](https://cloud.githubusercontent.com/assets/10557393/7307302/9d24a086-ea14-11e4-8b39-45fa1e89c3ee.jpg)

![atenholyorder2](https://cloud.githubusercontent.com/assets/10557393/7307306/a28ae8f0-ea14-11e4-9df8-7dcccdf09288.jpg)

**Comment by xirsoi** [comment]
Can you change the background on the upper one to white; darken the blue on the lower one, make the khopesh blade bronzier, and change the sun to be gold.

Looks good though! I like the sun beaming down onto the blade, blessing it with its power :+1:

**Comment by jbelig** [comment]
Like that?

![aten4](https://cloud.githubusercontent.com/assets/10557393/7312800/049bdbfe-ea5a-11e4-8718-e66ee8a7e82b.jpg)

![atenholyorder3](https://cloud.githubusercontent.com/assets/10557393/7312803/0eeda628-ea5a-11e4-9723-96ddc57c0c28.jpg)

**Comment by xirsoi** [comment]
Take it half a step back on the blue and its perfect!
When they're done, just email me the flags in tga (?) format and i'll drop them in.

**Comment by xirsoi** [comment]
https://upholdingmaat.wordpress.com/2013/07/09/the-epagomenal-days/

**Comment by xirsoi** [comment]
In my research around Atenism I found that Akhenaten established himself as the direct intermediary between mortals and Aten. All others were ordered to worship Akhenaten and Nefirtiri as living gods, who would then worship the Aten *for* the regular mortals.

This basically makes the Aten religious head a Caliph or Fylkir style title. I think this is a great way to differentiate the two. However, it means there is really no good gameplay reason to play a Kemetic (as opposed to an Atenic).

The only realistic downside I could think of would be lack of access to Patron Gods, but that isn't implemented yet. A friend suggested making successions more difficult somehow, perhaps by allowing close family members (anyone closer than kinsman) to have easy access to claims on the religious head title.

Any ideas?

**Comment by xirsoi** [comment]
Atens were made decadent, btw.

**Comment by xirsoi** [comment]
Closing this ticket because it's way too broad. Gonna make a couple more specific tickets for individual ideas.
