### ISSUE TITLE
Overriden vanilla decisions not working

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#46]
They are now detected by validator 1.9RC14, same behavior as previously seen on "Restore roman empire" decision, but for convert_to_attacker_religion and convert_to_reformed: the effect does nothing.

**Comment by rquinio** [comment]
I found a way to have convert_to_reformed completely generic, using:
- abandon_heresy command (no longer need to test every unreformed religion) 
- adding NOT = { is_reformed_religion = yes } test, so it doesn't show up for heresies of the reformed faith.
Tested that it doesn't appear for aten_pagan, but does for celtic_pagan (if faith was reformed).

**Comment by xirsoi** [comment]
Sounds good! It seems I haven't updated since RC12, so I didn't catch this when I was validating earlier this week.

**Comment by rquinio** [comment]
RC14 was just releases yesterday ^^
Closing as fixed !
