### ISSUE TITLE
paganify_the_world decision stays forever

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#47]
I've noticed that the decision continues to be available, after several days have passed since game start.
The global flag won't appear in allow tooltips but it would seem 
````had_global_flag = { flag = ancrel days = 1 } # only on first day````
is not working ?

Should the flag be set via hidden on_startup event ?

**Comment by xirsoi** [comment]
Its supposed to be set by the history. A character in the irish history file has an effect to set the global flag. zijistark thought it would work, even if they character is dead, but its clearly not.

We don't have an immortal god character like Isis, so we'll have to use an on_startup event, like i had originally done.

**Comment by xirsoi** [comment]
Fixed in develop
