### ISSUE TITLE
Rework the Fianna

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#52]
The Fianna currently are slightly wonky, in that they are a Holy Order when the legends make it clear they are mercenaries. Also, they do not require the age of crusades to begin, so they just might be the only Holy Order in the world when they are founded. As a result, they tend to grow much larger than other holy orders (they get a head start).

I propose that the Fianna should be both. If the Organize Fianna decision is made before the age of crusades has begun AND the religion is reformed, they are a mercenary company. Once both of those conditions are met, the Fianna is transformed into a holy order (a second title and an event to grant the HO and revoke the MC). This should reset their growth and make it more in line with the other Holy Orders. They can still be vassalized as normal.

What do you think?

**Comment by Mbites** [comment]
Basicly a good idea but it isn't possible to transform a mercenary into an Holy Order. You would need to create two Titles but thats actually not a big deal.

**Comment by xirsoi** [comment]
If you look above, you'll see I suggested that very thing.

**Comment by xirsoi** [comment]
Play testing should be done to make sure that this is still an issue after multiple edits to troop compositions.

**Comment by xirsoi** [comment]
The Fianna is fine.
