### ISSUE TITLE
Steam Workshop and releases

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#55]
@xirsoi Could you give us the "creator" permissions on the mod in the workshop ?
My user is http://steamcommunity.com/profiles/76561198048070550

Another random thought: we could name the next releases based on some ancient God name (high god for release, minor god for patch), would fit more in the theme :) What do you think ?

Btw we'll have to be careful about non-backward compatible releases on the workshop as mods auto-update and users can't revert.

**Comment by rquinio** [comment]
I did a commit to add tags and logo for the workshop https://github.com/xirsoi/ancientreligions/commit/22c9cf1b552a02417fd9dddfd0cad0b7d61e7c92, I used the one from the forum.
I was wondering if it wasn't misleading though, as it shows lots of religious symbols abd we only enhance 3 religions... But didn't have ideas for an alternative one :p

**Comment by xirsoi** [comment]
@jbelig if you have a steam account, friend me and I'll add you as a contributor.

I'll glob together the three images I have into a larger one.

How about high god names for major versions, 'regular' god names for minor, and heroes for patches?

I hadn't considered that issue. We'll have to be very careful about breaking changes in the future. Warning people about it on the forum won't be enough anymore. I imagine we'll have to sneak in breaking changes whenever Paradox puts out a major update. That or we might have to give giant warnings or something. Idk.

**Comment by xirsoi** [comment]
Okay, Major Versions will be the High God name of one of the supported religions. Minor version releases will be a random "minor" god from that pantheon. Patches will be a semi-divine/heroic/mortal character associated with that god.

So. I'm renaming Third Firecracker to Venus. Chosen randomly by fair die roll.
V0.36.1 will be "Adonis", a mortal hero she fell in love with and made immortal after his death.

Sound good to everyone?

**Comment by rquinio** [comment]
Sweet ! You should put a 1 sentence pitch about the chosen God, for general culture of the players xd

**Comment by rquinio** [comment]
I've seen @jbelig has been added too, so closing this, feel free to re-open if needed !
