### ISSUE TITLE
Bugs in Venus

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#56]
1) Sacred Dogs modifier is broken. @jbelig figured this out already and I think I know how to fix it.
2) Sacred Lake bonus is way too big. Currently at 80%, probably supposed to be %8, easy peasy 1-2-threesy.
3) Celtic characters who are already in Druidic training can ask to start Druidic training. Add condition to restrict the event from those with the Novice Druid trait.
4) A Child can ask to become a druid. Not sure about this, pretty sure the event has an age restriction. Should be an easy fix.
5) Child returns as an insane Druid assumes character is a man. Fix the localization, easy.

**Comment by xirsoi** [comment]
6) Promethean Pagans cannot hire women to any councilor job like the other feminist religions.
7) Druidic can be selected in Ruler Designer.
8) Epic Blood traits can be selected in ruler designer.

**Comment by xirsoi** [comment]
@rquinio, please review.

**Comment by rquinio** [comment]
@xirsoi Reviewed, see my comments on commits

**Comment by xirsoi** [comment]
9) b_mellifont is destroyed in the history files.
10) one of the kemetic holy sites does not exist in some starts

**Comment by rquinio** [comment]
For 9) not sure why b_mellifont (An Mhainistir Mhór) is a holy site , as it seems it was a Cistercian abbey founded in 1142 ! Found back this old thread on Celtic holy sites: http://forum.paradoxplaza.com/forum/showthread.php?689606-Holy-Sites-for-Celtic-Druidism&p=15512538&viewfull=1#post15512538

I think 10) is per design from CK2+: Luxor needs to be rebuilt via the decision (or simply by constructing a new temple holding in the province). I believe historically it was in pretty bad shape in CK2 timeframe, and it fits pretty well with a weak pre-reformed religion revived after hundreds of years.

**Comment by xirsoi** [comment]
b_mellifont was probably chosen because its a temple in Dublin (location of Tara) that exists from game start.

I don't think b_luxor exists at all though.
Like, it was added by CK2+.

I thought the game crashed when you opened the religion screen if there weren't 5 holy sites active?

**Comment by jbelig** [comment]
Luxor doesn't exist at all and the game doesn't crash. It just shows an empty slot until you build it. 
I thought there would be issues because all building slots in the province were used, but when I built it a new slot was added and everything was fine.

**Comment by rquinio** [comment]
b_luxor is defined in vanilla landed_titles.txt (inside c_asyut / d_aswan / k_egypt).

**Comment by xirsoi** [comment]
Okay, so 10) isn't actually a problem. Sweet!
I have b_mellifont fixed locally.

**Comment by xirsoi** [comment]
10) Sons of Gwydion formation event has localization bug at the very end. "the young, restless sons of Emperor."

Should be "the Empire" or "Prydain."

**Comment by xirsoi** [comment]
completed with Adonis update.
