### ISSUE TITLE
Restless Sidhe is Annoying

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#61]
It is quite frequent if you have a modest to large demense (4+), and a successful sacrifice to the Sidhe only removes the modifier from one province. It does seem that having completed a successful Sacrifice to the Sidhe increases the odds that the modifier will be removed by event.

The Sacrifice to the Sidhe mechanic is also kinda boring and un-fun. The ability to make a particularly large sacrifice, to increase the odds that you will get a good outcome, would be a nice addtion.

**Comment by rquinio** [comment]
Agreed, it's quite annoying for large realms.

**Comment by xirsoi** [comment]
Much better now.
