### ISSUE TITLE
Sidhe event localization is targeting province

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#63]
When the Restless Sidhe event (or others) fire for a Catholic province, you get things like "May the Blessed Virgin Protect us!", which is silly.

**Comment by xirsoi** [comment]
Still not fixed.

**Comment by rquinio** [comment]
Ha Root is a province... Maybe try [Root.Holder.Religion.GetRandomGodNameCap] ?

**Comment by xirsoi** [comment]
That's so weird, Root should be the ruler for that event, since they are the one who gets it.
Thanks for the tip, i'll give that a try!

**Comment by rquinio** [comment]
Indeed province_event are a bit weird, they fire for the province (ROOT) but it is the province owner who gets the event popup.
They should have used ROOT as the province owner, and FROM as the province, but too late !

**Comment by xirsoi** [comment]
Agreed. I'll test this fix on Monday or Tuesday night.
