### ISSUE TITLE
All Children are Reincarnated

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#65]
It looks like the main limiting factor is
NOT = {
  an_sibling = {
    is_reincarnated = yes
  }
}

But I think this doesn't catch half-siblings, as in, children by your wife and your concubines won't be counted as siblings of each other. This wasn't clear until my second ruler, because it also requires that one of your ancestors is dead.

**Comment by xirsoi** [comment]
Only way I can think to fix this is to check all children of the both parents.

**Comment by rquinio** [comment]
Or maybe re-introduce some random factor for on_birth on_action event (it's done like that in RoI) ?
Not sure what is best.

**Comment by xirsoi** [comment]
Hmm... I assumed that it was already random. I'll have to dig into it further.

**Comment by xirsoi** [comment]
You were right, it was in the list of events that always fire, not in the list of random events.
