### ISSUE TITLE
Hellenic Holy Orders and Merc Companies

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#67]
I believe CK2+ already has a holy order. We could port that first. When jbelig can do work again, we can introduce some of our own as well.

Sacred Band of Thebes. Could form when Thebes is Hellenic and moral authority is >60%. Have events where un-landed homosexuals who do not stand to inherit can request to join the band.

Myrmidons. Merc Company inspired by the legendary warriors of Achilles. They could pop when Aetolia is converted and moral authority is at least 50% (or something).

Any other ideas?
- [x] Sacred Band
- [x] Myrmidons
- Other ideas
  - [x] Hellenic Legion

**Comment by jbelig** [comment]
How about the Phalanx? It was the Macedonian evolution of the older Greek hoplites. It could be a merc company consisting of heavy infantry and heavy cavalry. In truth, the phalanx was just infantry, but it was always supported by cavalry else it was too exposed.
Thinking about it, this looks more appropriate for a retinue unit than a merc company to be honest.

**Comment by xirsoi** [comment]
Took a look at CK2+ holy orders for Hellenic, and they have the Sacred Band and an order called "Herculean." Not sure about the Herculean Order, but we should definitely port the Sacred Band.

**Comment by Mbites** [comment]
I already designed a Holy Order for the Hellenic Religion. I could just adjust some settings and then submit it to you.

**Comment by xirsoi** [comment]
Excellent, tell us about your holy order.

**Comment by Mbites** [comment]
Its in no way historic accurate but i could just rework the optical stuff thats not a big deal.
So the name is "Legio Hellenica". Its Heavy Infantry based (Imagine Roman Legions)
It spawns if Constantinople & Rome are under the control of any Hellenic Character.
Then a random soldier is spawned with roman culture and hellenic religion (obviously)

**Comment by xirsoi** [comment]
Interesting. Reminds me of another Roman Empire mod that lets you re-establish the old imperial provinces once you've fully conquered the territory. It would re-draw the de jure boundaries to reflect these old (kingdom level) territories. It would also let you create the old Legions as vassalized Mercenary companies, like the Varangian Guard.

**Comment by Mbites** [comment]
Here is a bit bigger version: 
http://puu.sh/h7l0f/d380e43365.jpg
Yeah, i planned that if the roman empire existed they could vassalize the holy order via Event/decision.

**Comment by xirsoi** [comment]
I'll be honest, I was going to tell you "Sorry, that order doesn't really make sense in the context of the mod." But seeing the fluff for that event, I'm all for it. The localisation is a little off, but I don't expect everyone to speak this bastard of a language perfectly ;)

Add it in the develop branch of your fork and submit a pull request to the develop branch of this repo.

**Comment by Mbites** [comment]
I did the localisation in 2 minutes i just didnt want an placeholder. I'll edit it if you want.

**Comment by xirsoi** [comment]
Edit for grammar and its fine. I like the gist of your fluff; that the *Legio Hellenica* is a long standing secret cult of Hellenism that, with the religion's return to the fore, is arming itself to defend the faith.

If you want to polish it up yourself, go ahead. Do you have a flag?

**Comment by Mbites** [comment]
I'll do that soon but unfortunatly i'am very busy with exams right now.

**Comment by xirsoi** [comment]
@Mbites, since you're busy, why don't you just submit a pull request to develop and I'll do any cleanup that's needed. I'd like to get moving on Vulcan and get it out the door soon.

**Comment by Mbites** [comment]
I'am very sorry, i'am trying to get myself use to github. But i'll try to get my stuff done now.

**Comment by xirsoi** [comment]
@jbelig would you be able to put together a flag for the Myrmidons? I'm imagining crossed spears behind a stereotypical spartan helm. A simple black on tan design, reminiscent of old attic vases.

**Comment by jbelig** [comment]
Hey, I don't play the game (or any game actually) any more, so I don't remember details like size or name format. 
Free time is really short, but you got me on a rare easy night so I've put something quick together from a tattoo design I found. Let me know what you think...

**Comment by jbelig** [comment]
Or something like that?

**Comment by xirsoi** [comment]
I don't see any images.

**Comment by xirsoi** [comment]
All three proposed mercenaries/holy orders have been added.
