### ISSUE TITLE
Crusade Weights

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#69]
There are no Crusade Weights for our three religions.
Landed Titles are additive, so we should be able to create an ACR_crusade_weights.txt with a definition for every single kingdom, and only include the crusade weights as properties.

I suggest that we give Crusade Weights to a majority of the kingdoms.

**Comment by rquinio** [comment]
JonStryker mentioned it was additive, though I've never tested outside of baronies.
Don't know if it matters that ACR_crusade_weights.txt would come first before landed_titles.txt, as there's no 00_ prefix ? Probably not.

**Comment by xirsoi** [comment]
Way back in like 1.11 they mentioned that landed titles properties were now additive. I think it would have caused greater celebration in the modding community if it was clear what exactly that meant. I think only now do people realize how awesome it is.

It shouldn't be an issue. I'm not changing an existing property.

This is as good a place as any to mention this. Anything done for Vulcan should be in a feature branch, in case we need to release Phaethon as a com-patch for CK2 v2.3.4

**Comment by xirsoi** [comment]
Also, those feature branches should NOT be merged into develop unless they are bug fixes. They should just hang until we are sure that develop and master are compatible with CK2 v2.3.4

**Comment by xirsoi** [comment]
@rquinio and @jbelig, please take a look at my branch and let me know what you think.
Feel free to ask me about my reasoning for any of them.

**Comment by xirsoi** [comment]
This screws up your flag cache, btw.

**Comment by jbelig** [comment]
I took a quick look today. Since k_jerusalem was part of the egyptian empire, shouldn't it have a large wight for kemetic?

**Comment by rquinio** [comment]
Looks good ! Just the typo on k_jerusalem for egyptian_pagan (missing 0) that jbelig spotted.
What's the benefit of weight 1 vs no weight ? Should the AI declare great holy wars on kingdoms it wouldn't care about ?

**Comment by xirsoi** [comment]
I debated that quite a bit, and decided that its better to let them declare the GHW on far off kingdoms, should all other targets already be Druidic. At that stage, those far off kingdoms would be directly bordering Druidic realms, and would thus be a threat (consider the Northern Crusade(?) against the Baltic pagans. Not important to the Catholic faith, but they were heathens on their borders and needed to be converted by the sword).

Thanks for the k_jerusalem catch, is definitely a typo.

**Comment by xirsoi** [comment]
I've changed my mind. I replaced all the weight 1's with weight 0's.

In the future, if we want, we can update these without having to manually enter all the religions.

**Comment by rquinio** [comment]
Ok ! Anyway that's pretty much a corner case, and a conquer the world scenario (except maybe with paganify decision).
