### ISSUE TITLE
Moving Celtic Holy Sites

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#71]
I believe the Holy Site in Galloway should be removed in favor of another one in France. Perhaps even in the Po River Valley (northern Italy). Currently it is stupid easy to reform the Celtic faith if you start in the Isles. I accomplished it with my second ruler and only having 4 provinces be actually Celtic.

**Comment by xirsoi** [comment]
I found an awesome place! The Springs of Sequana are found near http://fr.wikipedia.org/wiki/Ch%C3%A2tillon-sur-Seine and was the site of intense Celtic worship on the continent. Huge numbers of votive offerings were found in the waters here.

Unfortunately, the nearest in game location to Chatillon sur Seine is 70km away. In fact, there are multiple 'baronies' that are ~70km away. I'm starting to think that pilgrimages should be available for all three religions. There are far more really cool sacred places than just 5 (for holy sites). I mean, The Stone of Scone man!

**Comment by xirsoi** [comment]
Another possibility is Auray, Vannes, Brittany. Closest in-game barony to Carnac, site of a huge number of ancient megaliths.

**Comment by jbelig** [comment]
Isn't Vannes already a holy place?

**Comment by xirsoi** [comment]
Well shucks, you're right! I'll just make b_citeaux the holy site then. Its in Dijon and its a temple. Close-a-freakin-nuff.

**Comment by xirsoi** [comment]
Citeaux doesn't get built in the history files until 1098, should I move its building date to before the earliest start, or should I make a Luxor-style decision to rebuild it for Celtic rulers?

My gut tells me the latter, since there really wasn't any kind of temple at the location since the 5th century. I also don't want to have too many mechanics/events be shared between our religions.

Opinions?

**Comment by jbelig** [comment]
From a gameplay point of view, I always like more flavor decisions.
From a historical point of view, was this really such an important place that would justify such a decision (as was Luxor)? 
Perhaps this can be bypassed by a smart text though. Maybe our celtic ruler wants to leave his mark and decides to build a temple that will be the greatest of all?

**Comment by xirsoi** [comment]
The Springs of Sequana were pretty major; hundreds of offerings have been found in the waters there. There is a two thousand year old statue of the goddess there as well. Multiple bronze statues were recovered there.

A Celtic reconquest of ~~France~~ Gaul would stumble upon this site and would likely want to build a temple here. There are few other locations with as much ritual significance to the Celtic people outside of the Isles.

**Comment by xirsoi** [comment]
Also, I've bypassed the problem by moving the holy site to Autun, which is a temple built before the earliest start date.
