### ISSUE TITLE
Tribal Councilor Localization

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#74]
Like Republics, Tribal realms require their own localization or it defaults to Christian. Tribal Celtcs probably shouldn't have "Court Chaplains", for instance.

**Comment by Mbites** [comment]
Maybe something easy like "High Priest, High Druid" ?

**Comment by xirsoi** [comment]
I'm just going to copy the regular Celtic localization.

**Comment by xirsoi** [comment]
Fixed in Beroe
