### ISSUE TITLE
Events to get Bards

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#81]
Right now its exceptionally difficult to have a Court Bard. A true return to the ancient ways of the Celts would mean whole academies would be built to train bards.

I propose, at minimum, a decision to invite a bard to your court

I also propose an occasional event that lets you bring a bard into your court. According to legend, Bards would sometimes... overstay their welcome. Law stated that you *had* to provide for a bard, and his entourage, while they stayed in your realm. This could get expensive. Court Bards should have a slightly higher income than normal minor titles.

We should probably make some kind of events that grant a benefit for having a court bard, but that's another issue.

**Comment by rquinio** [comment]
Agreed, more ways to generate bards is needed !
Currently the only way is Druidic education (40% chances of poet trait).

**Comment by xirsoi** [comment]
Forgot to tag the issue in commit 177931e2aaa1e4c4f2ba5b3956d96a93ef53a836, but it adds an event to randomly get a bard.

I consider this issue complete.
