### ISSUE TITLE
Wolf Tails not appearing

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#83]
It was reported on the forum that the Wolf Tails won't appear if reforming Celtic faith before any province had converted.

I think ancrel.0280 can be reworked to fire either for:
- celtic_pagan if religion is not reformed
- OR celtic_pagan_formed
and use ROOT to reference the actual religion in the create_character commands.

**Comment by xirsoi** [comment]
Marking this as fixed with @rquinio 's update.
