### ISSUE TITLE
Neoplatonist Schools

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#86]
Skeptic, Stoic, Epicurian.

Could probably work like the Asha'rite and Muta'zalite schools in Islam. On adulthood you can choose a school to follow. Access to decisions allowing you to switch once every so many years at the cost of piety.

- [x] Create Traits (and icons)
- [x] Events to get one on adulthood (ai weights!)
- [x] Decision to pick a school (for certain non-Promethean scholars and/or mystics)
 - Should also be available to switch schools periodically (5 years?)

**Comment by xirsoi** [comment]
This would be for Prometheans mainly. Hellenes should get the ability to choose a school, but it should be more restricted since its not central to there belief system like it is with Prometheans.

**Comment by rquinio** [comment]
Interesting !
Not sure how Epicurean should relate to the vanilla Hedonist lifestyle.

**Comment by xirsoi** [comment]
It shouldn't. Epicurean is hedonist in only the most technical sense. They believed true happiness could only be obtained through pleasure, but that the greatest pleasure was avoiding pain. Including the inevitable pain of excess. They weren't exactly party animals ;)

Many of them were even vegetarian (because Epicurus was, not because anything in their beliefs dictated it).

**Comment by xirsoi** [comment]
Forgot to tag this issue when I made them, but the three traits were added in 0.37 and 0.37.1.

Flavor events for acquiring them and attaining a state of Henosis ("one-ness") would be awesome.

**Comment by xirsoi** [comment]
This task is complete!
